<?php echo $this->doctype(); ?>

<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta charset="utf-8">
<!-- Styles -->
<link href="template/css/bootstrap.css" rel="stylesheet">
<link href="template/css/bootstrap-respo/nsive.css" rel="stylesheet">
<link href="template/css/bootstrap-overrides.css" rel="stylesheet">

<link href="template/css/ui-lightness/jquery-ui-1.8.21.custom.css" rel="stylesheet">

<link href="template/css/slate.css" rel="stylesheet">
<link href="template/css/slate-responsive.css" rel="stylesheet">

<link href="template/css/pages/dashboard.css" rel="stylesheet">


<!-- Javascript -->
<script src="template/js/jquery-1.7.2.min.js"></script>
<script src="template/js/jquery-ui-1.8.21.custom.min.js"></script>
<script src="template/js/jquery.ui.touch-punch.min.js"></script>
<script src="template/js/bootstrap.js"></script>

<script src="template/js/Slate.js"></script>

<script src="template/js/plugins/excanvas/excanvas.min.js"></script>
<script src="template/js/plugins/flot/jquery.flot.js"></script>
<script src="template/js/plugins/flot/jquery.flot.orderBars.js"></script>
<script src="template/js/plugins/flot/jquery.flot.pie.js"></script>
<script src="template/js/plugins/flot/jquery.flot.resize.js"></script>

<script src="template/js/demos/charts/bar.js"></script>


<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

</head>

<body>


<div id="header">

    <div class="container">

        <h1><a href="template/">Slate Admin 2.0</a></h1>

        <div id="info">

            <a href="javascript:;" id="info-trigger">
                <i class="icon-cog"></i>
            </a>

            <div id="info-menu">

                <div class="info-details">

                    <h4>Olá, Waldir.</h4>

                    <p>
                        Logged in as Admin.
                        <br>
                        You have <a href="javascript:;">5 messages.</a>
                    </p>

                </div> <!-- /.info-details -->

                <div class="info-avatar">

                    <img src="template/img/avatar.jpg" alt="avatar">

                </div> <!-- /.info-avatar -->

            </div> <!-- /#info-menu -->

        </div> <!-- /#info -->

    </div> <!-- /.container -->

</div> <!-- /#header -->


<div id="nav">

    <div class="container">

        <a href="javascript:;" class="btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <i class="icon-reorder"></i>
        </a>

        <div class="nav-collapse">

            <ul class="nav">

                <li class="nav-icon active">
                    <a href="template/">
                        <i class="icon-home"></i>
                        <span>Home</span>
                    </a>
                </li>

                <li class="dropdown">
                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="icon-th"></i>
                        File
                        <b class="caret"></b>
                    </a>

                    <ul class="dropdown-menu">
                        <li><a href="template/forms.html">Config</a></li>
                        <li><a href="template/ui-elements.html">Ordem de Serviço</a></li>

                    </ul>
                </li>






            </ul>


            <ul class="nav pull-right">

                <li class="">
                    <form class="navbar-search pull-left">
                        <input type="text" class="search-query" placeholder="Search">
                        <button class="search-btn"><i class="icon-search"></i></button>
                    </form>
                </li>

            </ul>

        </div> <!-- /.nav-collapse -->

    </div> <!-- /.container -->

</div> <!-- /#nav -->


<div id="content">
    <?php echo $this->content; ?>

</div> <!-- /#content -->



<div id="footer">

    <div class="container">

        &copy; 2012 Propel UI, all rights reserved.

    </div> <!-- /.container -->

</div> <!-- /#footer -->





</body>
</html>
