<?php
/**
 * Zend Framework (http://framework.zend.com/)
 *
 * @link      http://github.com/zendframework/ZendSkeletonApplication for the canonical source repository
 * @copyright Copyright (c) 2005-2014 Zend Technologies USA Inc. (http://www.zend.com)
 * @license   http://framework.zend.com/license/new-bsd New BSD License
 */

namespace Config\Controller;

use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;

class IndexController extends AbstractActionController
{
    public function indexAction() {

        $idiomas = array(

            "af" => 'Africâner - ‪Afrikaans‬',
            "de" => 'Alemão - ‪Deutsch‬',
            "am" => 'Amárico - ‪አማርኛ‬',
            "ar" => 'Árabe - ‫العربية‬',
            "eu" => 'Basco - ‪euskara‬',
            "bn" => 'Bengali - ‪বাংলা‬',
            "bg" => 'Búlgaro - ‪български‬',
            "kn" => 'Canarês - ‪ಕನ್ನಡ‬',
            "ca" => 'Catalão - ‪català‬',
            "zh-HK" => 'Chinês (Hong Kong) - ‪中文（香港）‬',
            "zh-CN" => 'Chinês (simplificado) - ‪简体中文‬',
            "zh-TW" => 'Chinês (tradicional) - ‪繁體中文‬',
            "ko" => 'Coreano - ‪한국어‬',
            "hr" => 'Croata - ‪Hrvatski‬',
            "da" => 'Dinamarquês - ‪Dansk‬',
            "sk" => 'Eslovaco - ‪Slovenčina‬',
            "sl" => 'Esloveno - ‪slovenščina‬',
            "es-419" => 'Espanhol (América Latina) - ‪Español (Latinoamérica)‬',
            "es" => 'Espanhol (Espanha) - ‪Español (España)‬',
            "et" => 'Estoniano - ‪eesti‬',
            "fil" => 'Filipino',
            "fi" => 'Finlandês - ‪Suomi‬',
            "fr-CA" => 'Francês (Canadá) - ‪Français (Canada)‬',
            "fr" => 'Francês (França) - ‪Français (France)‬',
            "gl" => 'Galego - ‪galego‬',
            "el" => 'Grego - ‪Ελληνικά‬',
            "gu" => 'Guzerate - ‪ગુજરાતી‬',
            "iw" => 'Hebraico - ‫עברית‬',
            "hi" => 'Híndi - ‪हिन्दी‬',
            "nl" => 'Holandês - ‪Nederlands‬',
            "hu" => 'Húngaro - ‪magyar‬',
            "id" => 'Indonésio - ‪Bahasa Indonesia‬',
            "en" => 'Inglês (Estados Unidos) - ‪English (United States)‬',
            "en-GB" => 'Inglês (Reino Unido) - ‪English (United Kingdom)‬',
            "is" => 'Islandês - ‪íslenska‬',
            "it" => 'Italiano',
            "ja" => 'Japonês - ‪日本語‬',
            "lv" => 'Letão - ‪latviešu‬',
            "lt" => 'Lituano - ‪lietuvių‬',
            "ml" => 'Malaiala - ‪മലയാളം‬',
            "ms" => 'Malaio - ‪Bahasa Melayu‬',
            "mr" => 'Marata - ‪मराठी‬',
            "no" => 'Norueguês - ‪norsk‬',
            "or" => 'Oriya - ‪ଓଡ଼ିଆ‬',
            "fa" => 'Persa - ‫فارسی‬',
            "pl" => 'Polonês - ‪polski‬',
            "pt-BR" => 'Português (Brasil)',
            "pt-PT" => 'Português (Portugal)',
            "ro" => 'Romeno - ‪română‬',
            "ru" => 'Russo - ‪Русский‬',
            "sr" => 'Sérvio - ‪Српски‬',
            "sw" => 'Suaíli - ‪Kiswahili‬',
            "sv" => 'Sueco - ‪Svenska‬',
            "th" => 'Tailandês - ‪ไทย‬',
            "ta" => 'Tâmil - ‪தமிழ்‬',
            "cs" => 'Tcheco - ‪Čeština‬',
            "te" => 'Telugu - ‪తెలుగు‬',
            "tr" => 'Turco - ‪Türkçe‬',
            "uk" => 'Ucraniano - ‪Українська‬',
            "ur" => 'Urdu - ‫اردو‬',
            "vi" => 'Vietnamita - ‪Tiếng Việt‬',
            "zu" => 'Zulu - ‪isiZulu‬');

        $moedas = array (

            "BEL" => "Belgian Franc (financial)",
            "BZD" => "Belize Dollar",
            "XOF" => "CFA Franc BCEAO",
            "BMD" => "Bermudian Dollar",
            "INR" => "Indian Rupee",
            "BTN" => "Ngultrum",
            "BOP" => "Bolivian peso",
            "BOB" => "Boliviano",
            "BOV" => "Mvdol",
            "BAM" => "Convertible Marks",
            "BWP" => "Pula",
            "NOK" => "Norwegian Krone",
            "BRC" => "Brazilian cruzado",
            "BRB" => "Brazilian cruzeiro",
            "BRL" => "Brazilian Real",
            "BND" => "Brunei Dollar",
            "BGN" => "Bulgarian Lev",
            "BGJ" => "Bulgarian lev A/52",
            "BGK" => "Bulgarian lev A/62",
            "BGL" => "Bulgarian lev A/99",
            "BIF" => "Burundi Franc",
            "KHR" => "Riel",
            "XAF" => "CFA Franc BEAC",
            "CAD" => "Canadian Dollar",
            "CVE" => "Cape Verde Escudo",
            "KYD" => "Cayman Islands Dollar",
            "CLP" => "Chilean Peso",
            "CLF" => "Unidades de fomento",
            "CNX" => "Chinese People's Bank dollar",
            "CNY" => "Yuan Renminbi",
            "COP" => "Colombian Peso",
            "COU" => "Unidad de Valor real",
            "KMF" => "Comoro Franc",
            "CDF" => "Franc Congolais",
            "NZD" => "New Zealand Dollar",
            "CRC" => "Costa Rican Colon",
            "HRK" => "Croatian Kuna",
            "CUP" => "Cuban Peso",
            "CYP" => "Cyprus Pound",
            "CZK" => "Czech Koruna",
            "CSK" => "Czechoslovak koruna",
            "CSJ" => "Czechoslovak koruna A/53",
            "DKK" => "Danish Krone",
            "DJF" => "Djibouti Franc",
            "DOP" => "Dominican Peso",
            "ECS" => "Ecuador sucre",
            "EGP" => "Egyptian Pound",
            "SVC" => "Salvadoran colón",
            "EQE" => "Equatorial Guinean ekwele",
            "ERN" => "Nakfa",
            "EEK" => "Kroon",
            "ETB" => "Ethiopian Birr",
            "FKP" => "Falkland Island Pound",
            "FJD" => "Fiji Dollar",
            "FIM" => "Finnish Markka",
            "FRF" => "French Franc",
            "XFO" => "Gold-Franc",
            "XPF" => "CFP Franc",
            "GMD" => "Dalasi",
            "GEL" => "Lari",
            "DDM" => "East German Mark of the GDR (East Germany)",
            "DEM" => "Deutsche Mark",
            "GHS" => "Ghana Cedi",
            "GHC" => "Ghanaian cedi",
            "GIP" => "Gibraltar Pound",
            "GRD" => "Greek Drachma",
            "GTQ" => "Quetzal",
            "GNF" => "Guinea Franc",
            "GNE" => "Guinean syli",
            "GWP" => "Guinea-Bissau Peso",
            "GYD" => "Guyana Dollar",
            "HTG" => "Gourde",
            "HNL" => "Lempira",
            "HKD" => "Hong Kong Dollar",
            "HUF" => "Forint",
            "ISK" => "Iceland Krona",
            "ISJ" => "Icelandic old krona",
            "IDR" => "Rupiah",
            "IRR" => "Iranian Rial",
            "IQD" => "Iraqi Dinar",
            "IEP" => "Irish Pound (Punt in Irish language)",
            "ILP" => "Israeli lira",
            "ILR" => "Israeli old sheqel",
            "ILS" => "New Israeli Sheqel",
            "ITL" => "Italian Lira",
            "JMD" => "Jamaican Dollar",
            "JPY" => "Yen",
            "JOD" => "Jordanian Dinar",
            "KZT" => "Tenge",
            "KES" => "Kenyan Shilling",
            "KPW" => "North Korean Won",
            "KRW" => "Won",
            "KWD" => "Kuwaiti Dinar",
            "KGS" => "Som",
            "LAK" => "Kip",
            "LAJ" => "Lao kip",
            "LVL" => "Latvian Lats",
            "LBP" => "Lebanese Pound",
            "LSL" => "Loti",
            "ZAR" => "Rand",
            "LRD" => "Liberian Dollar",
            "LYD" => "Libyan Dinar",
            "CHF" => "Swiss Franc",
            "LTL" => "Lithuanian Litas",
            "LUF" => "Luxembourg Franc (currency union with BEF)",
            "MOP" => "Pataca",
            "MKD" => "Denar",
            "MKN" => "Former Yugoslav Republic of Macedonia denar A/93",
            "MGA" => "Malagasy Ariary",
            "MGF" => "Malagasy franc",
            "MWK" => "Kwacha",
            "MYR" => "Malaysian Ringgit",
            "MVQ" => "Maldive rupee",
            "MVR" => "Rufiyaa",
            "MAF" => "Mali franc",
            "MTL" => "Maltese Lira",
            "MRO" => "Ouguiya",
            "MUR" => "Mauritius Rupee",
            "MXN" => "Mexican Peso",
            "MXP" => "Mexican peso",
            "MXV" => "Mexican Unidad de Inversion (UDI)",
            "MDL" => "Moldovan Leu",
            "MCF" => "Monegasque franc (currency union with FRF)",
            "MNT" => "Tugrik",
            "MAD" => "Moroccan Dirham",
            "MZN" => "Metical",
            "MZM" => "Mozambican metical",
            "MMK" => "Kyat",
            "NAD" => "Namibia Dollar",
            "NPR" => "Nepalese Rupee",
            "NLG" => "Netherlands Guilder",
            "ANG" => "Netherlands Antillian Guilder",
            "NIO" => "Cordoba Oro",
            "NGN" => "Naira",
            "OMR" => "Rial Omani",
            "PKR" => "Pakistan Rupee",
            "PAB" => "Balboa",
            "PGK" => "Kina",
            "PYG" => "Guarani",
            "YDD" => "South Yemeni dinar",
            "PEN" => "Nuevo Sol",
            "PEI" => "Peruvian inti",
            "PEH" => "Peruvian sol",
            "PHP" => "Philippine Peso",
            "PLZ" => "Polish zloty A/94",
            "PLN" => "Zloty",
            "PTE" => "Portuguese Escudo",
            "TPE" => "Portuguese Timorese escudo",
            "QAR" => "Qatari Rial",
            "RON" => "New Leu",
            "ROL" => "Romanian leu A/05",
            "ROK" => "Romanian leu A/52",
            "RUB" => "Russian Ruble",
            "RWF" => "Rwanda Franc",
            "SHP" => "Saint Helena Pound",
            "WST" => "Tala",
            "STD" => "Dobra",
            "SAR" => "Saudi Riyal",
            "RSD" => "Serbian Dinar",
            "CSD" => "Serbian Dinar",
            "SCR" => "Seychelles Rupee",
            "SLL" => "Leone",
            "SGD" => "Singapore Dollar",
            "SKK" => "Slovak Koruna",
            "SIT" => "Slovenian Tolar",
            "SBD" => "Solomon Islands Dollar",
            "SOS" => "Somali Shilling",
            "ZAL" => "South African financial rand (Funds code) (discont",
            "ESP" => "Spanish Peseta",
            "ESA" => "Spanish peseta (account A)",
            "ESB" => "Spanish peseta (account B)",
            "LKR" => "Sri Lanka Rupee",
            "SDD" => "Sudanese Dinar",
            "SDP" => "Sudanese Pound",
            "SDG" => "Sudanese Pound",
            "SRD" => "Surinam Dollar",
            "SRG" => "Suriname guilder",
            "SZL" => "Lilangeni",
            "SEK" => "Swedish Krona",
            "CHE" => "WIR Euro",
            "CHW" => "WIR Franc",
            "SYP" => "Syrian Pound",
            "TWD" => "New Taiwan Dollar",
            "TJS" => "Somoni",
            "TJR" => "Tajikistan ruble",
            "TZS" => "Tanzanian Shilling",
            "THB" => "Baht",
            "TOP" => "Pa'anga",
            "TTD" => "Trinidata and Tobago Dollar",
            "TND" => "Tunisian Dinar",
            "TRY" => "New Turkish Lira",
            "TRL" => "Turkish lira A/05",
            "TMM" => "Manat",
            "RUR" => "Russian rubleA/97",
            "SUR" => "Soviet Union ruble",
            "UGX" => "Uganda Shilling",
            "UGS" => "Ugandan shilling A/87",
            "UAH" => "Hryvnia",
            "UAK" => "Ukrainian karbovanets",
            "AED" => "UAE Dirham",
            "GBP" => "Pound Sterling",
            "USN" => "US Dollar (Next Day)",
            "USS" => "US Dollar (Same Day)",
            "UYU" => "Peso Uruguayo",
            "UYN" => "Uruguay old peso",
            "UYI" => "Uruguay Peso en Unidades Indexadas",
            "UZS" => "Uzbekistan Sum",
            "VUV" => "Vatu",
            "VEF" => "Bolivar Fuerte",
            "VEB" => "Venezuelan Bolivar",
            "VND" => "Dong",
            "VNC" => "Vietnamese old dong",
            "YER" => "Yemeni Rial",
            "YUD" => "Yugoslav Dinar",
            "YUM" => "Yugoslav dinar (new)",
            "ZRN" => "Zairean New Zaire",
            "ZRZ" => "Zairean Zaire",
            "ZMK" => "Kwacha",
            "ZWD" => "Zimbabwe Dollar",
            "ZWC" => "Zimbabwe Rhodesian dollar"

        ) ;

        $timezone = array (

            "-12" => '(GMT-12:00) International Date Line West',
            "-11" => '(GMT-11:00) Midway Island, Samoa',
            "-10" => '(GMT-10:00) Hawaii',
            "-9" => '(GMT-09:00) Alaska',
            "-8" => '(GMT-08:00) Pacific Time (US & Canada)',
            "-8" => '(GMT-08:00) Tijuana, Baja California',
            "-7" => '(GMT-07:00) Arizona',
            "-7" => '(GMT-07:00) Chihuahua, La Paz, Mazatlan',
            "-7" => '(GMT-07:00) Mountain Time (US & Canada)',
            "-6" => '(GMT-06:00) Central America',
            "-6" => '(GMT-06:00) Central Time (US & Canada)',
            "-6" => '(GMT-06:00) Guadalajara, Mexico City, Monterrey',
            "-6" => '(GMT-06:00) Saskatchewan',
            "-5" => '(GMT-05:00) Bogota, Lima, Quito, Rio Branco',
            "-5" => '(GMT-05:00) Eastern Time (US & Canada)',
            "-5" => '(GMT-05:00) Indiana (East)',
            "-4" => '(GMT-04:00) Atlantic Time (Canada)',
            "-4" => '(GMT-04:00) Caracas, La Paz',
            "-4" => '(GMT-04:00) Manaus',
            "-4" => '(GMT-04:00) Santiago',
            "-3.5" => '(GMT-03:30) Newfoundland',
            "-3" => '(GMT-03:00) Brasilia',
            "-3" => '(GMT-03:00) Buenos Aires, Georgetown',
            "-3" => '(GMT-03:00) Greenland',
            "-3" => '(GMT-03:00) Montevideo',
            "-2" => '(GMT-02:00) Mid-Atlantic',
            "-1" => '(GMT-01:00) Cape Verde Is.',
            "-1" => '(GMT-01:00) Azores',
            "0" => '(GMT+00:00) Casablanca, Monrovia, Reykjavik',
            "0" => '(GMT+00:00) Greenwich Mean Time : Dublin, EdinburghLondon</option>',
            "1" => '(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm/option>',
            "1" => '(GMT+01:00) Belgrade, Bratislava, Budapest, Ljublja</option>',
            "1" => '(GMT+01:00) Brussels, Copenhagen, Madrid, Paris',
            "1" => '(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb',
            "1" => '(GMT+01:00) West Central Africa',
            "2" => '(GMT+02:00) Amman',
            "2" => '(GMT+02:00) Athens, Bucharest, Istanbul',
            "2" => '(GMT+02:00) Beirut',
            "2" => '(GMT+02:00) Cairo',
            "2" => '(GMT+02:00) Harare, Pretoria',
            "2" => '(GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn/option>',
            "2" => '(GMT+02:00) Jerusalem',
            "2" => '(GMT+02:00) Minsk',
            "2" => '(GMT+02:00) Windhoek',
            "3" => '(GMT+03:00) Kuwait, Riyadh, Baghdad',
            "3" => '(GMT+03:00) Moscow, St. Petersburg, Volgograd',
            "3" => '(GMT+03:00) Nairobi',
            "3" => '(GMT+03:00) Tbilisi',
            "3.5" => '(GMT+03:30) Tehran',
            "4" => '(GMT+04:00) Abu Dhabi, Muscat',
            "4" => '(GMT+04:00) Baku',
            "4" => '(GMT+04:00) Yerevan',
            "4.5" => '(GMT+04:30) Kabul',
            "5" => '(GMT+05:00) Yekaterinburg',
            "5" => '(GMT+05:00) Islamabad, Karachi, Tashkent',
            "5.5" => '(GMT+05:30) Sri Jayawardenapura',
            "5.5" => '(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi',
            "5.75" => '(GMT+05:45) Kathmandu',
            "6" => '(GMT+06:00) Almaty, Novosibirsk',
            "6" => '(GMT+06:00) Astana, Dhaka',
            "6.5" => '(GMT+06:30) Yangon (Rangoon)',
            "7" => '(GMT+07:00) Bangkok, Hanoi, Jakarta',
            "7" => '(GMT+07:00) Krasnoyarsk',
            "8" => '(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi',
            "8" => '(GMT+08:00) Kuala Lumpur, Singapore',
            "8" => '(GMT+08:00) Irkutsk, Ulaan Bataar',
            "8" => '(GMT+08:00) Perth',
            "8" => '(GMT+08:00) Taipei',
            "9" => '(GMT+09:00) Osaka, Sapporo, Tokyo',
            "9" => '(GMT+09:00) Seoul',
            "9" => '(GMT+09:00) Yakutsk',
            "9.5" => '(GMT+09:30) Adelaide',
            "9.5" => '(GMT+09:30) Darwin',
            "10" => '(GMT+10:00) Brisbane',
            "10" => '(GMT+10:00) Canberra, Melbourne, Sydney',
            "10" => '(GMT+10:00) Hobart',
            "10" => '(GMT+10:00) Guam, Port Moresby',
            "10" => '(GMT+10:00) Vladivostok',
            "11" => '(GMT+11:00) Magadan, Solomon Is., New Caledonia',
            "12" => '(GMT+12:00) Auckland, Wellington',
            "12" => '(GMT+12:00) Fiji, Kamchatka, Marshall Is.',
            "13" => '(GMT+13:00) Nuku alofa'
        );

        return new ViewModel(array(
                                    "timezone" => $timezone,
                                    "idiomas" => $idiomas,
                                    "moedas" => $moedas


            )


        );
    }

    public function cadastroAction() {

        echo "<pre>";
        print_r($_POST);

        print_r($this->getRequest()->getPost());

        die;
    }

}
